/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import negocio.cargador.Cargador;
import negocio.ui.UIGenExa;



/**
 *
 * @author M-01
 */
public class FrGenExa extends javax.swing.JFrame {

    private UIGenExa ui;
    /**
     * Creates new form FrGenExa
     */
    public FrGenExa() {
        initComponents();
        ui = new UIGenExa(this);
        Cargador.cargarTipoPregunta(cbTipoPregunta);
        this.setLocationRelativeTo(null);
        Cargador.cargarPreguntas(this.tbPreguntas, ui.getListaPreguntas());
        Cargador.cargarTbCategorías(tbCategorías, ui.getListaCategorías());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gpdf = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        JPPreguntas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPreguntas = new javax.swing.JTable();
        btnConsultarPregunta = new javax.swing.JButton();
        lblCodigoPregunta = new javax.swing.JLabel();
        txtIdPregunta = new javax.swing.JTextField();
        btnAgregarPregunta = new javax.swing.JButton();
        btnModificarPregunta = new javax.swing.JButton();
        sepPregunta = new javax.swing.JSeparator();
        cbTipoPregunta = new javax.swing.JComboBox();
        lblTipoPregunta = new javax.swing.JLabel();
        JPExamen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbExámenes = new javax.swing.JTable();
        JPCategorías = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCategorías = new javax.swing.JTable();
        lblIDCategoría = new javax.swing.JLabel();
        txtIDCategoría = new javax.swing.JTextField();
        btnConsultarCategoría = new javax.swing.JButton();
        btnModificarCategoría = new javax.swing.JButton();
        btnAgregarCategoría = new javax.swing.JButton();
        txtNuevaCategoría = new javax.swing.JTextField();
        txtModificarCategoría = new javax.swing.JTextField();
        sepCategoría = new javax.swing.JSeparator();
        lblNuevaCategoría = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuGuardarPDF = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        gpdf.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GenExa");
        setBounds(new java.awt.Rectangle(0, 0, 550, 360));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 530, 310));
        setMaximumSize(null);
        setMinimumSize(null);
        setName("GenExa"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(685, 530));

        JPPreguntas.setMaximumSize(new java.awt.Dimension(530, 310));
        JPPreguntas.setMinimumSize(new java.awt.Dimension(530, 310));

        tbPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbPreguntas);

        btnConsultarPregunta.setBackground(new java.awt.Color(204, 204, 0));
        btnConsultarPregunta.setText("Consultar ID");
        btnConsultarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPreguntaActionPerformed(evt);
            }
        });

        lblCodigoPregunta.setText("ID");

        btnAgregarPregunta.setBackground(new java.awt.Color(0, 153, 0));
        btnAgregarPregunta.setText("Agregar Nueva");
        btnAgregarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPreguntaActionPerformed(evt);
            }
        });

        btnModificarPregunta.setBackground(new java.awt.Color(0, 153, 153));
        btnModificarPregunta.setText("Modificar Seleccionada");
        btnModificarPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPreguntaActionPerformed(evt);
            }
        });

        cbTipoPregunta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipoPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPreguntaActionPerformed(evt);
            }
        });

        lblTipoPregunta.setText("Tipo de Pregunta");

        javax.swing.GroupLayout JPPreguntasLayout = new javax.swing.GroupLayout(JPPreguntas);
        JPPreguntas.setLayout(JPPreguntasLayout);
        JPPreguntasLayout.setHorizontalGroup(
            JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPreguntasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JPPreguntasLayout.createSequentialGroup()
                            .addGroup(JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JPPreguntasLayout.createSequentialGroup()
                                    .addComponent(lblCodigoPregunta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtIdPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnConsultarPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPPreguntasLayout.createSequentialGroup()
                                    .addComponent(lblTipoPregunta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbTipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnModificarPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgregarPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(sepPregunta))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        JPPreguntasLayout.setVerticalGroup(
            JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPreguntasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCodigoPregunta)
                    .addComponent(txtIdPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificarPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(JPPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAgregarPregunta)
                    .addComponent(cbTipoPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoPregunta))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preguntas", JPPreguntas);

        JPExamen.setMaximumSize(new java.awt.Dimension(530, 310));
        JPExamen.setMinimumSize(new java.awt.Dimension(530, 310));

        tbExámenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbExámenes.setMaximumSize(new java.awt.Dimension(300, 64));
        tbExámenes.setMinimumSize(new java.awt.Dimension(300, 64));
        jScrollPane1.setViewportView(tbExámenes);

        javax.swing.GroupLayout JPExamenLayout = new javax.swing.GroupLayout(JPExamen);
        JPExamen.setLayout(JPExamenLayout);
        JPExamenLayout.setHorizontalGroup(
            JPExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPExamenLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        JPExamenLayout.setVerticalGroup(
            JPExamenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPExamenLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exámenes", JPExamen);

        JPCategorías.setMaximumSize(new java.awt.Dimension(530, 310));
        JPCategorías.setMinimumSize(new java.awt.Dimension(530, 310));

        tbCategorías.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCategorías.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCategoríasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbCategorías);

        lblIDCategoría.setText("ID");

        btnConsultarCategoría.setBackground(new java.awt.Color(204, 204, 0));
        btnConsultarCategoría.setText("Consultar ID");
        btnConsultarCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCategoríaActionPerformed(evt);
            }
        });

        btnModificarCategoría.setBackground(new java.awt.Color(0, 153, 153));
        btnModificarCategoría.setText("Modificar Seleccionada");
        btnModificarCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarCategoríaActionPerformed(evt);
            }
        });

        btnAgregarCategoría.setBackground(new java.awt.Color(0, 153, 0));
        btnAgregarCategoría.setText("Agregar Nueva");
        btnAgregarCategoría.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoríaActionPerformed(evt);
            }
        });

        lblNuevaCategoría.setText(" Nueva Categoría:");

        javax.swing.GroupLayout JPCategoríasLayout = new javax.swing.GroupLayout(JPCategorías);
        JPCategorías.setLayout(JPCategoríasLayout);
        JPCategoríasLayout.setHorizontalGroup(
            JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCategoríasLayout.createSequentialGroup()
                .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPCategoríasLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPCategoríasLayout.createSequentialGroup()
                                .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(JPCategoríasLayout.createSequentialGroup()
                                        .addComponent(lblIDCategoría)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIDCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConsultarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtModificarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNuevaCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPCategoríasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModificarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JPCategoríasLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(btnAgregarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(JPCategoríasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNuevaCategoría)
                            .addComponent(sepCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        JPCategoríasLayout.setVerticalGroup(
            JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCategoríasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblIDCategoría)
                    .addComponent(txtIDCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCategoría)
                    .addComponent(txtModificarCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarCategoría))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sepCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(JPCategoríasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnAgregarCategoría)
                    .addComponent(txtNuevaCategoría, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaCategoría))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Categorías", JPCategorías);

        jMenu1.setText("File");

        jMenuAbrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuAbrir.setText("Abrir");
        jMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrir);

        jMenuGuardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardar);

        jMenuGuardarPDF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuGuardarPDF.setText("Guardar (pdf)");
        jMenuGuardarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarPDFActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuGuardarPDF);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void refrescarListaPreguntas(){
        Cargador.cargarPreguntas(this.tbPreguntas, ui.getListaPreguntas());
    }
    
    private void refrescarListaCategorías(){
        Cargador.cargarTbCategorías(this.tbCategorías, ui.getListaCategorías());
    }
    
    private void btnModificarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPreguntaActionPerformed

        String tipo;
        int selected;
        int ID;
        
        selected = this.tbPreguntas.getSelectedRow();
       //Escoge el tipo de Pregunta
       if(selected >= 0){
            tipo = this.tbPreguntas.getValueAt(selected, 1).toString();
            ID = Integer.parseInt(this.tbPreguntas.getValueAt(selected, 2).toString());

            if( tipo.equals("datos.Pregunta") ){
                    DiPreguntaDesarrollo PD = new DiPreguntaDesarrollo(this, true, ui, false);
                    Cargador.cargarPreguntaDesarrollo(PD, ui.consultarPregunta(ID));
                    PD.setVisible(true);
            }else{
                if( tipo.equals("datos.VerdaderoFalso") ){
                    DiPreguntaVF PVF = new DiPreguntaVF(this, true, ui, false);
                    Cargador.cargarPreguntaVF(PVF, ui.consultarPregunta(ID));
                    PVF.setVisible(true);
                }else{
                    if( tipo.equals("datos.SeleccionUnica") ){
                    DiPreguntaSU SU = new DiPreguntaSU(this, true, ui, false);
                    Cargador.cargarPreguntaSU(SU, ui.consultarPregunta(ID));
                    SU.setVisible(true);
                    }
                }
           }

        }
        
       refrescarListaPreguntas(); 
    }//GEN-LAST:event_btnModificarPreguntaActionPerformed

    private void btnAgregarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPreguntaActionPerformed
        int tipoPregunta = this.cbTipoPregunta.getSelectedIndex();
        
        switch(tipoPregunta){
            case 0: DiPreguntaDesarrollo PD = new DiPreguntaDesarrollo(this, true, ui, true);
                    PD.setVisible(true);
            break;
            case 1: DiPreguntaVF PVF = new DiPreguntaVF(this, true, ui, true);
                    PVF.setVisible(true);
            break;
            case 2: DiPreguntaSU SU = new DiPreguntaSU(this, true, ui, true);
                    SU.setVisible(true);
            break;
        }
        
        refrescarListaPreguntas();
        
    }//GEN-LAST:event_btnAgregarPreguntaActionPerformed

    private void btnConsultarPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPreguntaActionPerformed
        int ID = Integer.parseInt(this.getTxtId().getText());
        int tipo = ui.consultarTipoPregunta(ID);
        switch(tipo){
            case 0:
                    DiPreguntaDesarrollo PD = new DiPreguntaDesarrollo(this, true, ui, false);
                    Cargador.cargarPreguntaDesarrollo(PD, ui.consultarPregunta(ID));
                    PD.setVisible(true);
                break;
            case 1:
                    DiPreguntaVF PVF = new DiPreguntaVF(this, true, ui, false);
                    Cargador.cargarPreguntaVF(PVF, ui.consultarPregunta(ID));
                    PVF.setVisible(true);
                break;
            case 2:
                    DiPreguntaSU PSU = new DiPreguntaSU(this, true, ui, false);
                    Cargador.cargarPreguntaSU(PSU, ui.consultarPregunta(ID));
                    PSU.setVisible(true);
                break;
        }
        refrescarListaPreguntas();
    }//GEN-LAST:event_btnConsultarPreguntaActionPerformed

    private void cbTipoPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoPreguntaActionPerformed

    private void btnConsultarCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCategoríaActionPerformed
        ui.consultarCategoría(this);
    }//GEN-LAST:event_btnConsultarCategoríaActionPerformed

    private void btnModificarCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarCategoríaActionPerformed
        ui.modificarCategoría(this);
        refrescarListaCategorías();
    }//GEN-LAST:event_btnModificarCategoríaActionPerformed

    private void btnAgregarCategoríaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoríaActionPerformed
        ui.agregarCategoría(this);
        refrescarListaCategorías();
    }//GEN-LAST:event_btnAgregarCategoríaActionPerformed

    private void tbCategoríasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCategoríasMouseClicked
        int i = this.tbCategorías.getSelectedRow();
        if (i > -1){
            this.txtIDCategoría.setText(this.tbCategorías.getValueAt(i, 0).toString());
            this.txtModificarCategoría.setText(this.tbCategorías.getValueAt(i, 1).toString());
        }
    }//GEN-LAST:event_tbCategoríasMouseClicked

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuGuardarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarPDFActionPerformed
        // TODO add your handling code here:
        gpdf.showSaveDialog(jMenu1);
        File pdf = gpdf.getSelectedFile();
        ui.crearPDF(pdf);
        
    }//GEN-LAST:event_jMenuGuardarPDFActionPerformed

    private void jMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirActionPerformed
        // TODO add your handling code here:
        gpdf.showOpenDialog(jMenu1);
        File file = gpdf.getSelectedFile();
        ui.cargarArchivo(file);
    }//GEN-LAST:event_jMenuAbrirActionPerformed

    public JComboBox getCbTipoPregunta() {
        return cbTipoPregunta;
    }

    public void setCbTipoPregunta(JComboBox cbTipoPregunta) {
        this.cbTipoPregunta = cbTipoPregunta;
    }

    public JTextField getTxtId() {
        return txtIdPregunta;
    }

    public void setTxtId(JTextField txtId) {
        this.txtIdPregunta = txtId;
    }

    public JTable getTbPreguntas() {
        return tbPreguntas;
    }

    public JTable getTbCategorías() {
        return tbCategorías;
    }

    public void setTbCategorías(JTable tbCategorías) {
        this.tbCategorías = tbCategorías;
    }

    public JTextField getTxtIDCategoría() {
        return txtIDCategoría;
    }

    public void setTxtIDCategoría(JTextField txtIDCategoría) {
        this.txtIDCategoría = txtIDCategoría;
    }

    public JTextField getTxtModificarCategoría() {
        return txtModificarCategoría;
    }

    public void setTxtModificarCategoría(JTextField txtModificarCategoría) {
        this.txtModificarCategoría = txtModificarCategoría;
    }

    public JTextField getTxtNuevaCategoría() {
        return txtNuevaCategoría;
    }

    public void setTxtNuevaCategoría(JTextField txtNuevaCategoría) {
        this.txtNuevaCategoría = txtNuevaCategoría;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrGenExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrGenExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrGenExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrGenExa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrGenExa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPCategorías;
    private javax.swing.JPanel JPExamen;
    private javax.swing.JPanel JPPreguntas;
    private javax.swing.JButton btnAgregarCategoría;
    private javax.swing.JButton btnAgregarPregunta;
    private javax.swing.JButton btnConsultarCategoría;
    private javax.swing.JButton btnConsultarPregunta;
    private javax.swing.JButton btnModificarCategoría;
    private javax.swing.JButton btnModificarPregunta;
    private javax.swing.JComboBox cbTipoPregunta;
    private javax.swing.JFileChooser gpdf;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuAbrir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuGuardarPDF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodigoPregunta;
    private javax.swing.JLabel lblIDCategoría;
    private javax.swing.JLabel lblNuevaCategoría;
    private javax.swing.JLabel lblTipoPregunta;
    private javax.swing.JSeparator sepCategoría;
    private javax.swing.JSeparator sepPregunta;
    private javax.swing.JTable tbCategorías;
    private javax.swing.JTable tbExámenes;
    private javax.swing.JTable tbPreguntas;
    private javax.swing.JTextField txtIDCategoría;
    private javax.swing.JTextField txtIdPregunta;
    private javax.swing.JTextField txtModificarCategoría;
    private javax.swing.JTextField txtNuevaCategoría;
    // End of variables declaration//GEN-END:variables
}
